version: "3"

services:
  api-node-js:
    image: postgres
    container_name: nodejs
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432